### PR TITLE
Bump protobuf and protobuf-codegen from ~2.0 -> ~2.1

### PR DESCRIPTION
**Pull request by dwerner**
I wanted to bump these versions to get the  the newly added `serde_derive` support in generated code. stepancheg/rust-protobuf brings this in as of 2.1.

### CODE REVIEW

**Comment by ice1000** [comment]
@overvenus @BusyJay Please take a look

**Comment by overvenus** [comment]
PTAL @hicqu, thanks!

**Comment by dwerner** [comment]
Nice, builds now.

**Comment by peterhuene** [comment]
Thanks for this!  Any chance this can get into a new release of `grpcio-compiler`?  I have another reason for getting a bumped protobuf: clean clippy builds with protobuf 2.1.3.

**Comment by BusyJay** [comment]
Is any incompatible changes introduced in 2.1? I recall that the version is limited to 2.0.x to prevent any such issue happen again. See also #182.

**Comment by hicqu** [comment]
According to https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md

**Comment by hicqu** [comment]
According to https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md, seems no new code-gen issues are introduced.
LGTM.

**Pull request merged**
