### PR TITLE
Document OpenSSL compatibility issue and fix

### PR DESCRIPTION
**Pull request by mandreyel**
Fixes: #339

### CODE REVIEW

**Comment by BusyJay** [comment]
Can you move it after section "feature secure"? So that they are more organized.

**Comment by mandreyel** [comment]
@BusyJay done.

**Comment by ice1000** [comment]
Please fix CI

**Comment by BusyJay** [comment]
I don't think the CI is related to the changes. It's from prost.

/cc @nrc @ice1000 Now that protobuf-build is published on crates.io, can it be kept stable? I have seen it broken from time to time.

**Comment by nrc** [comment]
It should be fixed since earlier today. Perhaps we can add some of the downstream crates to protobuf-build's CI? It is a bit of a pain to test at the moment :-(

**Comment by ice1000** [comment]
> /cc @nrc @ice1000 Now that protobuf-build is published on crates.io, can it be kept stable? I have seen it broken from time to time.

Sorry for the breakage -- but it happens only once, though 3-4 (IIRC) PRs are affected so it looks like "broken from time to time".

**Pull request merged**
