### PR TITLE
Use Git dep for Prost

### PR DESCRIPTION
**Pull request by nrc**
Use a Git dep for Prost so we get some optimisations which are not present in the current release.

PTAL @ice1000 @overvenus

### CODE REVIEW

**Comment by ice1000** [comment]
```
0.38s$ cargo build
The command "cargo build" exited with 101.
0.22s$ cargo test --all
The command "cargo test --all" exited with 101.
before_cache
0.11s$ find $TRAVIS_BUILD_DIR/target/debug -maxdepth 1 -type f -delete
cache.2
store build cache
216.50serror: failed to parse manifest at `C:\Users\travis\build\pingcap\grpc-rs\proto\Cargo.toml`
Caused by:
  Dependency 'prost' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.
error: failed to parse manifest at `C:\Users\travis\build\pingcap\grpc-rs\proto\Cargo.toml`
Caused by:
  Dependency 'prost' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.
```

Maybe need to modify `proto`'s dependency as well

**Comment by ice1000** [comment]
Let's see what does the CI say this time

**Comment by ice1000** [comment]
FYI `travis_wait` can let travis ci to wait a longer period of time

**Comment by brson** [comment]
Pre-emptive LGTM pending ci

**Comment by nrc** [comment]
CI is green, PTAL @ice1000

**Comment by nrc** [comment]
@brson ping to make your review official so this can be merged :-)

**Pull request merged**
