### PR TITLE
build: support build and test on windows

### PR DESCRIPTION
**Pull request by BusyJay**
After this pr, this project should be able to be built and tested on windows. We may need to adopt Appveyor CI later.

If you are using Visual Studio 2017, you may need to use latest nightly rustc to build any rust program.

If you meet code page related error, you may need to set environment `_CL_` to "/utf-8".

### CODE REVIEW

**Comment by siddontang** [comment]
Do we need to support windows in CI too?

**Comment by BusyJay** [comment]
Yes. As said in the pr description, I will introduce Appveyor later.

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @overvenus

**Pull request merged**
