### PR TITLE
c-wrap: fix memory leak

### PR DESCRIPTION
**Pull request by BusyJay**
ref: https://github.com/grpc/grpc/commit/06eb057eb76d62ca6ee0987b9b2fae1befbff78a

### CODE REVIEW

**Comment by siddontang** [comment]
PTAL @overvenus

**Comment by overvenus** [comment]
@sre-bot r+

**Comment by BusyJay** [comment]
@sre-bot r+

**Comment by siddontang** [comment]
CI failed @BusyJay

**Comment by BusyJay** [comment]
@sre-bot retry this too. Thx.

**Comment by BusyJay** [comment]
I guess it should be able to be merged now, @sre-bot how about retry it another time?

**Pull request merged**
