### PR TITLE
Upgrade grpc to v1.8

### PR DESCRIPTION
**Pull request by overvenus**

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Comment by ngaut** [comment]
Please fix CI

**Comment by BusyJay** [comment]
Let's upgrade it to 1.8.4, which fixes some core issues.

**Comment by BusyJay** [comment]
How about the performance impact?

**Comment by overvenus** [comment]
| | rust_generic_async_streaming_ping_pong |
| -- | --- |
|1.7.2| QPS: 22320.7 |
|1.8.6| QPS: 23048.5 |

**Comment by siddontang** [comment]
@overvenus 

Do we use 1.8.6 now or still 1.8.4?

**Comment by overvenus** [comment]
1.8.6

**Comment by siddontang** [comment]
LGTM
Please fix the CI

**Comment by lhecker** [comment]
Just in case this is relevant: [gRPC 1.10 came out recently.](https://github.com/grpc/grpc/releases/tag/v1.10.0)

**Comment by BusyJay** [comment]
Thanks. @overvenus let's upgrade it to a more recent one.

**Comment by overvenus** [comment]
Closed in favor of #171.

**Pull request closed without merging**
