### PR TITLE
Improve  RPC client clonable.

### PR DESCRIPTION
**Pull request by hicqu**
I want to write code like this:
```rust
let stream1 = client.stream_rpc1(); // A new RPC interface.
client.spawn(
    stream1.send_all(...).then(|r| match r {
        Err(e) => {
            // The new RPC is not supported by server side, so fallback to an old RPC.
            let stream2 = client.stream_rpc2(); // need a copy of `Client` here.
            stream2.send_all(...)
        }
})
```
`Client` is already `Arc`ed. So I don't want to Arc it again.

### CODE REVIEW

**Comment by ice1000** [comment]
Any special requirement for copying the client? Like do we need to call some functions to ref and unref?

**Comment by overvenus** [comment]
Duplicate with #251 ?

**Comment by hicqu** [comment]
Closed by #251

**Comment by hicqu** [comment]
This PR can improve the old implemention in #251 . Clone the `Arc` inside the `Client` is better than make a new call.

**Pull request merged**
