### PR TITLE
Fix #316: support `-fno-omit-frame-pointer` flag via a feature

### LINKED ISSUE #316: grpc core is not built using -fno-omit-frame-pointer
According to DWARF info in my TiKV we can see that `-fno-omit-frame-pointer` is not passed when building gRPC, which will lead to `[unknown]`s in perf if it is in frame pointer mode.

```
< 0><0x0000000b>  DW_TAG_compile_unit
                    DW_AT_producer              GNU C++ 4.8.5 20150623 (Red Hat 4.8.5-28) -m64 -mtune=generic -march=x86-64 -g -O2 -std=c++11 -ffunction-sections -fdata-sections -fPIC -fno-exceptions -fno-rtti
                    DW_AT_language              DW_LANG_C_plus_plus
                    DW_AT_name                  /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.2/grpc/src/core/lib/gpr/string_posix.cc
                    DW_AT_comp_dir              /home/pingcap/wenxuan/tikv/target/release/build/grpcio-sys-4bb4c1382d45ffa7/out/build

< 0><0x0000000b>  DW_TAG_compile_unit
                    DW_AT_producer              GNU C 4.8.5 20150623 (Red Hat 4.8.5-28) -m64 -mtune=generic -march=x86-64 -g -O2 -ffunction-sections -fdata-sections -fPIC
                    DW_AT_language              DW_LANG_C89
                    DW_AT_name                  /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.2/grpc/third_party/cares/cares/ares__get_hostent.c
                    DW_AT_comp_dir              /home/pingcap/wenxuan/tikv/target/release/build/grpcio-sys-4bb4c1382d45ffa7/out/build/third_party/cares/cares
                    DW_AT_ranges                0x00f7b960
```

### PR DESCRIPTION
**Pull request by ice1000**
Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>

This PR addresses #316.

### CODE REVIEW

**Comment by breeswish** [comment]
Actually cc will automatically add this flag: https://github.com/alexcrichton/cc-rs/blob/0409188fad2c7b3413802a8421c59523c116d59d/src/lib.rs#L209

I have no idea why it doesn't work for this crate :)

**Comment by breeswish** [comment]
Ok so this flag was added since cc 1.0.19: https://github.com/alexcrichton/cc-rs/commit/ad7ee45081ac33ef77e90ed0208e1f91cacbc59f

**Comment by overvenus** [comment]
Can we pass the flag by env? `CXXFLAGS=-fno-omit-frame-pointer`

**Comment by breeswish** [comment]
@overvenus Yes I think so. I just suggesting that we should dig out why this flag was not added, so that we may learn from it and prevent this case in other projects.

**Comment by ice1000** [comment]
> Ok so this flag was added since cc 1.0.19: alexcrichton/cc-rs@ad7ee45

So we still have no idea why there's no such flag added right?
🤔

**Comment by breeswish** [comment]
@ice1000 Yes. Maybe it is related to cmake.

**Comment by ice1000** [comment]
@breeswish how can I determine if the flag is added after a compilation?

**Comment by breeswish** [comment]
@ice1000 I use `dwarfdump BINARY`. It will output the compiler command line for each source code unit. (The output file can be pretty huge though)

**Comment by ice1000** [comment]
My personal guess: because we're using cc to compile `grpc_wrap.cc` but not the grpc core, we need to manually define the flag for cmake.
This is what I get in my testing project:

```
/home/VeryMoe/.cargo/bin/cargo run --color=always --package cmake-cc-rust --bin cmake-cc-rust
   Compiling cmake-cc-rust v0.1.0 (/home/VeryMoe/git-repos/cmake-cc-rust)
    Finished dev [unoptimized + debuginfo] target(s) in 0.87s
     Running `target/debug/cmake-cc-rust`
running: "cmake" "/home/VeryMoe/git-repos/cmake-cc-rust/." "-DCMAKE_INSTALL_PREFIX=cmake-build-debug" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=release"
```

Code:

```rust
use cc::Build;
use cmake::Config;
use std::env;

fn main() {
    env::set_var("OUT_DIR", "cmake-build-debug");
    let mut c = Config::new(".");
    c.host("").out_dir("cmake-build-debug").profile("release").target("").build_target("cmake-cc-rust").uses_cxx11().build();

    let mut cc = Build::new();
    cc.include(".");
    cc.cpp(true);
    cc.warnings(true);
    cc.file("wrap.cpp");
    cc.compile("libwrap.a");
}
```

**Comment by ice1000** [comment]
BTW c/cxx flags are separated. I'll add for cxx too

**Comment by ice1000** [comment]
The code is not properly configuring cmake but it has successfully displayed the flags it added

**Comment by ice1000** [comment]
CI passsed, PTAL @breeswish @overvenus

**Pull request merged**
