### PR TITLE
Create issue templates.

### PR DESCRIPTION
**Pull request by Hoverbear**
Add issue templates for bug reports and feature requests.

Let's come up with a common set of issue and PR templates between prometheus, raft, and grpc? What do you think @breeswish, @BusyJay ?

### CODE REVIEW

**Comment by siddontang** [comment]
why not using tikv's directly? https://github.com/tikv/tikv/tree/master/.github/ISSUE_TEMPLATE

**Comment by ice1000** [comment]
What's the current status of this PR? Is this PR dead?

**Comment by overvenus** [comment]
I don't think that will be necessary, eg, questions about grpc-rs do not acquire to read tikv's document. I will merge the PR in tomorrow if there is no objection.

**Comment by Hoverbear** [comment]
I fixed a couple small issues.

@overvenus I'd like to open the same PR on prometheus, failure, and Raft after we verify this works! So once you merge I'll do that next day. :)

**Comment by ice1000** [comment]
@overvenus It's not blocked by CI.

**Comment by Hoverbear** [comment]
Force pushed to force a rebuild since I can't do a rebuild from the webpage.

**Comment by overvenus** [comment]
Sorry for the inconvenience.
Could you merge it @siddontang ?

**Comment by overvenus** [comment]
Merged, thank you @Hoverbear

**Comment by Hoverbear** [comment]
:thinking: Seems the PR templates aren't working.

**Comment by Hoverbear** [comment]
Ah, https://github.com/pingcap/grpc-rs/compare/master...busyjay/limit-concurrency?template=feature.md neat.

**Pull request merged**
