### PR TITLE
Upgrade gRPC core library to 1.16.0

### PR DESCRIPTION
**Pull request by overvenus**
Please merge pingcap/grpc#15 first.

### CODE REVIEW

**Comment by Snnappie** [comment]
Any update on this? We currently have to build our project from a custom fork of this project and grpc that fixed this issue: https://github.com/grpc/grpc/pull/16415
(before it was fixed in main-line)
That change was introduced in grpc release 1.15.0, which is still later than the version used by grpc-rs.

**Comment by ice1000** [comment]
We're planning for a regression of grpc core due to tikv/tikv#3745, maybe maintaining two branches with different grpc version should be a possible solution.

**Comment by overvenus** [comment]
We plan to upgrade gRPC core to v1.16.x or [v1.17.x](https://github.com/pingcap/grpc-rs/tree/upgrade-1.17.0) once we resolves grpc/grpc#17043, which may cause segment fault.

**Comment by overvenus** [comment]
Closed in favour of #264  .

**Pull request closed without merging**
